### ISSUE TITLE
Setuptools 8.1.0 needed for a recent `git` change

### ISSUE THREAD

**Issue by jaimergp** [AnacondaRecipes/setuptools_scm-feedstock#8]
Details in https://github.com/pypa/setuptools_scm/issues/1038

Needed to fix breakage in `conda/conda` CI for Python <=3.10, I think? https://github.com/conda/conda/actions/runs/9881920885/job/27293763034?pr=14030

**Comment by skupr-anaconda** [comment]
`setuptools_scm 8.1.0` is available on the `defaults` channel

**Comment by jaimergp** [comment]
Thanks!
